### ISSUE TITLE
uninitialized constant Kernel::Bootscale

### ISSUE THREAD

**Issue by artofhuman** [byroot/bootscale#11] opened 2015-08-24 14:53 UTC
in my `config/boot.rb`

```
require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
require 'bootscale/setup'

time bundle exec rake environment
```

and i got error `uninitialized constant Kernel::Bootscale`

If

```
require 'bootscale
Bootscale.setup(cache_directory: File.expand_path('../../tmp/bootscale', __FILE__))
```

All good, but time decreased so small ;( 62,65s with bootscale vs 65.64,45s without

**Comment by byroot** [comment] 2015-08-24 14:58
Sorry you just got unlucky. We merged a change that is still unreleased. Since you are using 0.2.2 here's the correct README: https://github.com/byroot/bootscale/tree/v0.2.2

> 62,65s with bootscale vs 65.64,45s without

OMG. THis boot time is so slow that it can't be all require time. I assume you are doing a lot during initialization time.

If you have around 200-250 gems 3 seconds saved is all you can expect. The rest of your boot time must be network calls.

**Comment by grosser** [comment] 2015-08-24 16:30
60s what boot time ... wow ... give [bumbler](https://github.com/nevir/Bumbler) a try

**Comment by grosser** [comment] 2015-08-24 16:32
the issue is fixed now <-> close this ?

**Comment by byroot** [comment] 2015-08-24 16:39
Yes closing. @artofhuman as said before it seems your main problem is not really gem loading but other work done during boot.

**Closed as completed by byroot** 2015-08-24 16:39 UTC
